# workflow 의 이름
name: PR labeler

# 트리거될 이벤트 설정
on:
  pull_request_target:
    types: [opened]

# 트리거되었을 때 실행될 job 작성
jobs:
  labeler:
    # runner 설정
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.ES_US_TOKEN}}


